### ISSUE TITLE
AppRun script does not work

### ISSUE THREAD

**Issue by probonopd** [appimage-packages/artikulate#4]
Cannot run:

```
/tmp/.mount_RHVA3X/AppRun: 15: exec: : Permission denied
```

AppRun script is entirely messed up, it looks like all variables were replaced by nothing:

```
#!/bin/sh
HERE="/in"
export LD_PRELOAD=""/exec_wrapper.so
export QML2_IMPORT_PATH=""/qml
export QT_PLUGIN_PATH=""/plugins
export PATH=""/usr/bin/:""/usr/sbin/:""/usr/games/:""/bin/:""/sbin/:"/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export LD_LIBRARY_PATH=""/usr/lib/:""/usr/lib/x86_64-linux-gnu/:""/usr/lib64/:""/lib/:""/lib/x86_64-linux-gnu/:""/lib64/:""
export XDG_DATA_DIRS=""/usr/share:"/root"/.local/share:/usr/local/share/:/usr/share:""
export XDG_DATA_HOME="/root"/.local/share
export XDG_CONFIG_DIRS=""/etc/xdg:""
export KDE_FORK_SLAVES=1
export GST_PLUGIN_PATH=""/lib
export GST_PLUGIN_SCANNER=""/bin
EXEC=
exec "" 
```

**Comment by ScarlettGatelyMoore** [comment]
Not sure where this came from... My current working apprun is
cat > AppRun << EOF
#!/bin/sh
DIR="\`dirname \"\$0\"\`"
HERE="\`( cd \"\$DIR\" && pwd )\`"
export LD_PRELOAD=\$HERE/exec_wrapper.so
export QML2_IMPORT_PATH=\$HERE/qml
export QT_PLUGIN_PATH=\$HERE/plugins
export PATH=\$HERE/usr/bin/:\$HERE/usr/sbin/:\$HERE/usr/games/:\$HERE/bin/:\$HERE/sbin/:\$PATH
export LD_LIBRARY_PATH=\$HERE/usr/lib/:\$HERE/usr/lib/x86_64-linux-gnu/:\$HERE/usr/lib64/:\$HERE/lib/:\$HERE/lib/x86_64-linux-gnu/:\$HERE/lib64/:\$LD_LIBRARY_PATH
export XDG_DATA_DIRS=\$HERE/usr/share:\$HOME/.local/share:/usr/local/share:/usr/share:\$XDG_DATA_DIRS
export XDG_DATA_HOME=\$HOME/.local/share
export XDG_CONFIG_DIRS=\$HERE/etc/xdg:\$XDG_CONFIG_DIRS
export KDE_FORK_SLAVES=1
export GST_PLUGIN_PATH=\$HERE/lib
export GST_PLUGIN_SCANNER=\$HERE/bin

<%= name %> $@
EOF
chmod +x AppRun

That exec bit in your default failed miserably for our needs.
Please try the newest build. Thanks.

**Comment by probonopd** [comment]
Home jobs pipeline-artikulate-appimage master 148
	artikulate-no-data-git01092017-x86_64.AppImage

works but the Qt theme looks out of place in xubuntu-16.04-desktop-amd64.iso.

**Comment by ScarlettGatelyMoore** [comment]
works but the Qt theme looks out of place in xubuntu-16.04-desktop-amd64.iso.
I have no idea what you mean here. Could you elaborate. Closing this, please open a new bug.
